/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/visensa3d.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/visensa3d.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Root} />
      <skinnedMesh geometry={nodes['Body_(merged)'].geometry} material={materials['N00_000_00_Body_00_SKIN (Instance)']} skeleton={nodes['Body_(merged)'].skeleton} />
      <skinnedMesh geometry={nodes['Body_(merged)_1'].geometry} material={materials['N00_004_01_Tops_01_CLOTH (Instance)']} skeleton={nodes['Body_(merged)_1'].skeleton} />
    </group>
  )
}

useGLTF.preload('/visensa3d.glb')
