/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/vroid_arm.glb 
*/

import React, { useEffect } from 'react'
import { useGraph, useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'
import { useHandStore } from '../store/zustand/useHandStore'

const boneMap = {
  lower_arm: null,
  wrist: null,
  thumb_mcp: null,
  thumb_pip: null,
  thumb_dip: null,
  index_mcp: null,
  index_pip: null,
  index_dip: null,
  middle_mcp: null,
  middle_pip: null,
  middle_dip: null,
  ring_mcp: null,
  ring_pip: null,
  ring_dip: null,
  pinky_mcp: null,
  pinky_pip: null,
  pinky_dip: null,
};

const BONE_KEYS = Object.keys(boneMap);
const CURL_MULTIPLIER = 2.0;

// Per-bone damping — higher = faster but twitchier
const DAMPING = {
  lower_arm: 0.22,
  wrist: 0.18,
  default: 0.15,
};

const tempEuler = new THREE.Euler();
const tempQuaternion = new THREE.Quaternion();
const targetQuaternion = new THREE.Quaternion();
const initialRotations = {};

export function Model(props) {
  const { scene } = useGLTF('/models/vroid_arm.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  useEffect(() => {
    // 1. Mapping tulang VRM/VRoid ke sistem Kalidokit kita
    if (nodes) {
      boneMap.lower_arm = nodes.J_Bip_R_LowerArm;
      boneMap.wrist = nodes.J_Bip_R_Hand;
      boneMap.thumb_mcp = nodes.J_Bip_R_Thumb1;
      boneMap.thumb_pip = nodes.J_Bip_R_Thumb2;
      boneMap.thumb_dip = nodes.J_Bip_R_Thumb3;
      boneMap.index_mcp = nodes.J_Bip_R_Index1;
      boneMap.index_pip = nodes.J_Bip_R_Index2;
      boneMap.index_dip = nodes.J_Bip_R_Index3;
      boneMap.middle_mcp = nodes.J_Bip_R_Middle1;
      boneMap.middle_pip = nodes.J_Bip_R_Middle2;
      boneMap.middle_dip = nodes.J_Bip_R_Middle3;
      boneMap.ring_mcp = nodes.J_Bip_R_Ring1;
      boneMap.ring_pip = nodes.J_Bip_R_Ring2;
      boneMap.ring_dip = nodes.J_Bip_R_Ring3;
      boneMap.pinky_mcp = nodes.J_Bip_R_Little1; // VRoid menyebut kelingking 'Little'
      boneMap.pinky_pip = nodes.J_Bip_R_Little2;
      boneMap.pinky_dip = nodes.J_Bip_R_Little3;

      // Simpan posisi rotasi asli (T-Pose) dari VRoid
      for (let i = 0; i < BONE_KEYS.length; i++) {
        const key = BONE_KEYS[i];
        const bone = boneMap[key];
        if (bone) {
          initialRotations[key] = bone.quaternion.clone();
        }
      }
    }
  }, [nodes]);

  useFrame(() => {
    const pose = useHandStore.getState().handPose;
    if (!pose) return;

    for (let i = 0; i < BONE_KEYS.length; i++) {
      const key = BONE_KEYS[i];
      const bone = boneMap[key];
      const rotation = pose[key];
      const initial = initialRotations[key];

      if (bone && rotation && initial) {
        const isWrist = key === "wrist";
        
        // KARENA INI MODEL VRM, KALIDOKIT SUDAH MENGELUARKAN ROTASI YANG SEMPURNA
        // Tidak perlu axisMapping rumit, cukup passthrough raw data.
        let rotX = rotation.x;
        let rotY = rotation.y;
        let rotZ = rotation.z;

        // Inversi untuk menyesuaikan mirroring kamera (karena video di-flip css)
        const fingerName = key.split('_')[0];
        const currentCurlMultiplier = isWrist ? 1 : CURL_MULTIPLIER;
        
        // Coba tanpa inversi terlebih dahulu (karena T-Pose biasanya stabil)
        // Nanti bisa disesuaikan kalau ternyata jarinya kebalik.
        tempEuler.set(
          rotX, 
          rotY * currentCurlMultiplier, 
          -rotZ // VRM Z-axis biasanya kebalikan dari webgl standar
        );

        tempQuaternion.setFromEuler(tempEuler);
        targetQuaternion.copy(initial).multiply(tempQuaternion);

        const damping = DAMPING[key] || DAMPING.default;
        bone.quaternion.slerp(targetQuaternion, damping);
        bone.updateMatrixWorld(true);
      }
    }
  });

  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Root} />
      {/* Pastikan nama N00_000_00_Body... dll sesuai dengan file hasil npx gltfjsx Anda */}
      {nodes['Body_(merged)'] && (
        <skinnedMesh 
          geometry={nodes['Body_(merged)'].geometry} 
          material={materials['N00_000_00_Body_00_SKIN (Instance)']} 
          skeleton={nodes['Body_(merged)'].skeleton} 
        />
      )}
      {nodes['Body_(merged)_1'] && (
        <skinnedMesh 
          geometry={nodes['Body_(merged)_1'].geometry} 
          material={materials['N00_004_01_Tops_01_CLOTH (Instance)']} 
          skeleton={nodes['Body_(merged)_1'].skeleton} 
        />
      )}
    </group>
  )
}

useGLTF.preload('/models/vroid_arm.glb')
